---
<<<<<<< HEAD
- name: Install Python
=======
- name: Install Python1
>>>>>>> 98f52b0 (Initial commit)
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: install Flask and sql
  pip:
    name:
      - flask
      - flask-cors
      - mysql-connector-python
    executable: pip3

- name: Create a virtual env
  command: python3 -m venv /home/akash/flask_app/venv creates=/home/akash/flask_app/venv
  become: yes

- name: Install apps requiremnts
<<<<<<< HEAD
  pip: 
    requirements: /home/akash/flask_app/requirements.txt
    virtualenv: /home/akash/flask_app/venv

- name: copy flask app
  copy: 
    src: app.py
=======
  pip:
    requirements: /home/akash/flask_app/requirements.txt
    virtualenv: /home/akash/flask_app/venv
  become: yes

- name: copy flask app
  template: 
    src: app.py.j2
>>>>>>> 98f52b0 (Initial commit)
    dest: /home/akash/flask_app/app.py
    mode: '0755'


<<<<<<< HEAD

- name: start app
  shell: nohup /home/akash/flask_app/venv/bin/python /home/akash/flask_app/app.py &
=======
- name: start app
  shell: nohup /home/akash/flask_app/venv/bin/python /home/akash/flask_app/app.py > /home/akash/flask_app/app.log 2>&1 &
>>>>>>> 98f52b0 (Initial commit)
  args:
    chdir: /home/akash/flask_app
  become: yes









<<<<<<< HEAD

=======
>>>>>>> 98f52b0 (Initial commit)
