---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start and enable MySQL service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Create database and user
  mysql_db:
    name: ansibledb
    state: present
    login_user: root
    login_password: "040801"
    login_host: localhost

- name: Create database user
  mysql_user:
    name: akash
    password: akash
    priv: "*.*:ALL"
    state: present
    login_user: root
    login_password: "040801"
    login_host: localhost

